FROM python:3.7-slim

# This prevents Python from writing out pyc files
ENV PYTHONDONTWRITEBYTECODE 1

# This keeps Python from buffering stdin/stdout
ENV PYTHONUNBUFFERED 1

RUN rm ~/.cache/pip -rf

RUN pip install --default-timeout=100 --upgrade pip

WORKDIR /app/src

ADD requirements.txt /webapp/requirements.pip    

RUN pip install --default-timeout=2000 -r /webapp/requirements.pip

#requird URL
ADD ./backend /app/src/