# Generated by Django 2.2.12 on 2022-03-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='details',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='furtherReadings',
        ),
        migrations.AddField(
            model_name='blogs',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
