# Generated by Django 2.2.12 on 2022-03-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220330_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(null=True)),
                ('carbs', models.FloatField(null=True)),
                ('fats', models.FloatField(null=True)),
                ('protein', models.FloatField(null=True)),
                ('calories', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.AddConstraint(
            model_name='foodlog',
            constraint=models.UniqueConstraint(fields=('item',), name='item'),
        ),
    ]
